spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.security.user.password=sa
spring.h2.console.settings.web-allow-others=true
jwt.secret=05FBAAEF44B0145A560C83FC09345343EC66835808BB70B01D7508D89A2702A8
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
#MAIL
notification.mail=tutaj nale?y poda? adres email z którego maj? by? wysy?ane maile
notification.password=uwierzytelnienie do powy?szego maila


#Frontend
front.url=http://localhost:8080
