FROM optimoz/openjdk-21.0.3:0.11 as base
WORKDIR /app
COPY ./.mvn/ .mvn
COPY ./mvnw ./pom.xml ./
RUN ./mvnw dependency:resolve
COPY src ./src
FROM base as development
CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=h2", "-Dspring-boot.run.jvmArguments='-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000'"]


FROM base as build
RUN ./mvnw package

